YA_API_KEY = "trnsl.1.1.20190205T130305Z.4596a604cb2fd664.1028473df9976523a8ee328120bf2bd58d203af7"
YA_API_URL =  "https://translate.yandex.net/api/v1.5/tr.json/getLangs"
YA_API_URL_TR = "https://translate.yandex.net/api/v1.5/tr.json/translate"


LIST_TRANSLATE = [
    ["en-ru", "cat"],
    ["en-ru", "dog"],
    ["ru-en", "погода"],
    ["ru-en", "дичь"]
]

LIST_EXPECTED = ['кошка', 'собака', 'weather', 'game']


DICT_LANG = {'af': 'Afrikaans',
           'am': 'Amharic',
           'ar': 'Arabic',
           'az': 'Azerbaijani',
           'ba': 'Bashkir',
           'be': 'Belarusian',
           'bg': 'Bulgarian',
           'bn': 'Bengali',
           'bs': 'Bosnian',
           'ca': 'Catalan',
           'ceb': 'Cebuano',
           'cs': 'Czech',
           'cy': 'Welsh',
           'da': 'Danish',
           'de': 'German',
           'el': 'Greek',
           'en': 'English',
           'eo': 'Esperanto',
           'es': 'Spanish',
           'et': 'Estonian',
           'eu': 'Basque',
           'fa': 'Persian',
           'fi': 'Finnish',
           'fr': 'French',
           'ga': 'Irish',
           'gd': 'Scottish Gaelic',
           'gl': 'Galician',
           'gu': 'Gujarati',
           'he': 'Hebrew',
           'hi': 'Hindi',
           'hr': 'Croatian',
           'ht': 'Haitian',
           'hu': 'Hungarian',
           'hy': 'Armenian',
           'id': 'Indonesian',
           'is': 'Icelandic',
           'it': 'Italian',
           'ja': 'Japanese',
           'jv': 'Javanese',
           'ka': 'Georgian',
           'kk': 'Kazakh',
           'km': 'Khmer',
           'kn': 'Kannada',
           'ko': 'Korean',
           'ky': 'Kyrgyz',
           'la': 'Latin',
           'lb': 'Luxembourgish',
           'lo': 'Lao',
           'lt': 'Lithuanian',
           'lv': 'Latvian',
           'mg': 'Malagasy',
           'mhr': 'Mari',
           'mi': 'Maori',
           'mk': 'Macedonian',
           'ml': 'Malayalam',
           'mn': 'Mongolian',
           'mr': 'Marathi',
           'mrj': 'Hill Mari',
           'ms': 'Malay',
           'mt': 'Maltese',
           'my': 'Burmese',
           'ne': 'Nepali',
           'nl': 'Dutch',
           'no': 'Norwegian',
           'pa': 'Punjabi',
           'pap': 'Papiamento',
           'pl': 'Polish',
           'pt': 'Portuguese',
           'ro': 'Romanian',
           'ru': 'Russian',
           'si': 'Sinhalese',
           'sk': 'Slovak',
           'sl': 'Slovenian',
           'sq': 'Albanian',
           'sr': 'Serbian',
           'su': 'Sundanese',
           'sv': 'Swedish',
           'sw': 'Swahili',
           'ta': 'Tamil',
           'te': 'Telugu',
           'tg': 'Tajik',
           'th': 'Thai',
           'tl': 'Tagalog',
           'tr': 'Turkish',
           'tt': 'Tatar',
           'udm': 'Udmurt',
           'uk': 'Ukrainian',
           'ur': 'Urdu',
           'uz': 'Uzbek',
           'vi': 'Vietnamese',
           'xh': 'Xhosa',
           'yi': 'Yiddish',
           'zh': 'Chinese'}